import 'package:flutter/material.dart';

class ConciergeProPalette {
  const ConciergeProPalette._();

  static const Color surface = Color(0xFFF9F9FE);
  static const Color surfaceDim = Color(0xFFD9DADE);
  static const Color surfaceBright = Color(0xFFF9F9FE);
  static const Color surfaceContainerLowest = Color(0xFFFFFFFF);
  static const Color surfaceContainerLow = Color(0xFFF3F3F8);
  static const Color surfaceContainer = Color(0xFFEDEDF2);
  static const Color surfaceContainerHigh = Color(0xFFE8E8ED);
  static const Color surfaceContainerHighest = Color(0xFFE2E2E7);
  static const Color onSurface = Color(0xFF1A1C1F);
  static const Color onSurfaceVariant = Color(0xFF414755);
  static const Color inverseSurface = Color(0xFF2E3034);
  static const Color inverseOnSurface = Color(0xFFF0F0F5);
  static const Color outline = Color(0xFF717786);
  static const Color outlineVariant = Color(0xFFC1C6D7);
  static const Color surfaceTint = Color(0xFF005BC1);
  static const Color primary = Color(0xFF0058BC);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color primaryContainer = Color(0xFF0070EB);
  static const Color onPrimaryContainer = Color(0xFFFEFCFF);
  static const Color inversePrimary = Color(0xFFADC6FF);
  static const Color secondary = Color(0xFF006E28);
  static const Color onSecondary = Color(0xFFFFFFFF);
  static const Color secondaryContainer = Color(0xFF6FFB85);
  static const Color onSecondaryContainer = Color(0xFF00732A);
  static const Color tertiary = Color(0xFF4C4ACA);
  static const Color onTertiary = Color(0xFFFFFFFF);
  static const Color tertiaryContainer = Color(0xFF6664E4);
  static const Color onTertiaryContainer = Color(0xFFFFFBFF);
  static const Color error = Color(0xFFBA1A1A);
  static const Color onError = Color(0xFFFFFFFF);
  static const Color errorContainer = Color(0xFFFFDAD6);
  static const Color onErrorContainer = Color(0xFF93000A);
  static const Color primaryFixed = Color(0xFFD8E2FF);
  static const Color primaryFixedDim = Color(0xFFADC6FF);
  static const Color onPrimaryFixed = Color(0xFF001A41);
  static const Color onPrimaryFixedVariant = Color(0xFF004493);
  static const Color secondaryFixed = Color(0xFF72FE88);
  static const Color secondaryFixedDim = Color(0xFF53E16F);
  static const Color onSecondaryFixed = Color(0xFF002107);
  static const Color onSecondaryFixedVariant = Color(0xFF00531C);
  static const Color tertiaryFixed = Color(0xFFE2DFFF);
  static const Color tertiaryFixedDim = Color(0xFFC2C1FF);
  static const Color onTertiaryFixed = Color(0xFF0C006A);
  static const Color onTertiaryFixedVariant = Color(0xFF3631B4);
  static const Color background = Color(0xFFF9F9FE);
  static const Color onBackground = Color(0xFF1A1C1F);
  static const Color surfaceVariant = Color(0xFFE2E2E7);
}

class CupertinoGlassVisionPalette {
  const CupertinoGlassVisionPalette._();

  static const Color surface = Color(0xFFFAF9FE);
  static const Color surfaceDim = Color(0xFFDAD9DF);
  static const Color surfaceBright = Color(0xFFFAF9FE);
  static const Color surfaceContainerLowest = Color(0xFFFFFFFF);
  static const Color surfaceContainerLow = Color(0xFFF4F3F8);
  static const Color surfaceContainer = Color(0xFFEEEDF3);
  static const Color surfaceContainerHigh = Color(0xFFE9E7ED);
  static const Color surfaceContainerHighest = Color(0xFFE3E2E7);
  static const Color onSurface = Color(0xFF1A1B1F);
  static const Color onSurfaceVariant = Color(0xFF414755);
  static const Color inverseSurface = Color(0xFF2F3034);
  static const Color inverseOnSurface = Color(0xFFF1F0F5);
  static const Color outline = Color(0xFF717786);
  static const Color outlineVariant = Color(0xFFC1C6D7);
  static const Color surfaceTint = Color(0xFF005BC1);
  static const Color primary = Color(0xFF0058BC);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color primaryContainer = Color(0xFF0070EB);
  static const Color onPrimaryContainer = Color(0xFFFEFCFF);
  static const Color inversePrimary = Color(0xFFADC6FF);
  static const Color secondary = Color(0xFF006E28);
  static const Color onSecondary = Color(0xFFFFFFFF);
  static const Color secondaryContainer = Color(0xFF6FFB85);
  static const Color onSecondaryContainer = Color(0xFF00732A);
  static const Color tertiary = Color(0xFF4C4ACA);
  static const Color onTertiary = Color(0xFFFFFFFF);
  static const Color tertiaryContainer = Color(0xFF6664E4);
  static const Color onTertiaryContainer = Color(0xFFFFFBFF);
  static const Color error = Color(0xFFBA1A1A);
  static const Color onError = Color(0xFFFFFFFF);
  static const Color errorContainer = Color(0xFFFFDAD6);
  static const Color onErrorContainer = Color(0xFF93000A);
  static const Color primaryFixed = Color(0xFFD8E2FF);
  static const Color primaryFixedDim = Color(0xFFADC6FF);
  static const Color onPrimaryFixed = Color(0xFF001A41);
  static const Color onPrimaryFixedVariant = Color(0xFF004493);
  static const Color secondaryFixed = Color(0xFF72FE88);
  static const Color secondaryFixedDim = Color(0xFF53E16F);
  static const Color onSecondaryFixed = Color(0xFF002107);
  static const Color onSecondaryFixedVariant = Color(0xFF00531C);
  static const Color tertiaryFixed = Color(0xFFE2DFFF);
  static const Color tertiaryFixedDim = Color(0xFFC2C1FF);
  static const Color onTertiaryFixed = Color(0xFF0C006A);
  static const Color onTertiaryFixedVariant = Color(0xFF3631B4);
  static const Color background = Color(0xFFFAF9FE);
  static const Color onBackground = Color(0xFF1A1B1F);
  static const Color surfaceVariant = Color(0xFFE3E2E7);
}
